In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/Market_Basket_Optimisation.csv',header=None)

In [4]:
df.isna().sum()

0        0
1     1754
2     3112
3     4156
4     4972
5     5637
6     6132
7     6520
8     6847
9     7106
10    7245
11    7347
12    7414
13    7454
14    7476
15    7493
16    7497
17    7497
18    7498
19    7500
dtype: int64

In [5]:
transactions=[]
for i in range(0,len(df)):
  transactions.append(str(df.values[i,j]) for j in range(0,20) if df.values[i,j]!='nan')
transactions

[<generator object <genexpr> at 0x7acf46900740>,
 <generator object <genexpr> at 0x7acf3c1b8660>,
 <generator object <genexpr> at 0x7acf3c1b8900>,
 <generator object <genexpr> at 0x7acf3c1b84a0>,
 <generator object <genexpr> at 0x7acf3c1b82e0>,
 <generator object <genexpr> at 0x7acf3c1b8580>,
 <generator object <genexpr> at 0x7acf3c1b8820>,
 <generator object <genexpr> at 0x7acf3c1b83c0>,
 <generator object <genexpr> at 0x7acf3c1b8ac0>,
 <generator object <genexpr> at 0x7acf3c1b89e0>,
 <generator object <genexpr> at 0x7acf3c1b8ba0>,
 <generator object <genexpr> at 0x7acf3c1b8740>,
 <generator object <genexpr> at 0x7acf3c1b8200>,
 <generator object <genexpr> at 0x7acf3c1b9000>,
 <generator object <genexpr> at 0x7acf3c1b8e40>,
 <generator object <genexpr> at 0x7acf3c1b8d60>,
 <generator object <genexpr> at 0x7acf3c1b8f20>,
 <generator object <genexpr> at 0x7acf3c1b8c80>,
 <generator object <genexpr> at 0x7acf3c1b90e0>,
 <generator object <genexpr> at 0x7acf3c1b91c0>,
 <generator object <genexpr> at 0x7acf3c1b92a0>,
 <generator object <genexpr> at 0x7acf3c1b9380>,
 <generator object <genexpr> at 0x7acf3c1b9460>,
 <generator object <genexpr> at 0x7acf3c1b9540>,
 <generator object <genexpr> at 0x7acf3c1b9620>,
 <generator object <genexpr> at 0x7acf3c1b9700>,
 <generator object <genexpr> at 0x7acf3c1b97e0>,
 <generator object <genexpr> at 0x7acf3c1b98c0>,
 <generator object <genexpr> at 0x7acf3c1b99a0>,
 <generator object <genexpr> at 0x7acf3c1b9a80>,
 <generator object <genexpr> at 0x7acf3c1b9b60>,
 <generator object <genexpr> at 0x7acf3c1b9c40>,
 <generator object <genexpr> at 0x7acf3c1b9d20>,
 <generator object <genexpr> at 0x7acf3c1b9e00>,
 <generator object <genexpr> at 0x7acf3c1b9ee0>,
 <generator object <genexpr> at 0x7acf3c1b9fc0>,
 <generator object <genexpr> at 0x7acf3c1ba0a0>,
 <generator object <genexpr> at 0x7acf3c1ba180>,
 <generator object <genexpr> at 0x7acf3c1ba260>,
 <generator object <genexpr> at 0x7acf3c1ba340>,
 <generator object <genexpr> at 0x7acf3c1ba420>,
 <generator object <genexpr> at 0x7acf3c1ba500>,
 <generator object <genexpr> at 0x7acf3c1ba5e0>,
 <generator object <genexpr> at 0x7acf3c1ba6c0>,
 <generator object <genexpr> at 0x7acf3c1ba7a0>,
 <generator object <genexpr> at 0x7acf3c1ba880>,
 <generator object <genexpr> at 0x7acf3c1ba960>,
 <generator object <genexpr> at 0x7acf3c1baa40>,
 <generator object <genexpr> at 0x7acf3c1bab20>,
 <generator object <genexpr> at 0x7acf3c1bac00>,
 <generator object <genexpr> at 0x7acf3c1bace0>,
 <generator object <genexpr> at 0x7acf3c1badc0>,
 <generator object <genexpr> at 0x7acf3c1baea0>,
 <generator object <genexpr> at 0x7acf3c1baf80>,
 <generator object <genexpr> at 0x7acf3c1bb060>,
 <generator object <genexpr> at 0x7acf3c1bb140>,
 <generator object <genexpr> at 0x7acf3c1bb220>,
 <generator object <genexpr> at 0x7acf3c1bb300>,
 <generator object <genexpr> at 0x7acf3c1bb3e0>,
 <generator object <genexpr> at 0x7acf3c1bb4c0>,
 <generator object <genexpr> at 0x7acf3c1bb5a0>,
 <generator object <genexpr> at 0x7acf3c1bb680>,
 <generator object <genexpr> at 0x7acf3c1bb760>,
 <generator object <genexpr> at 0x7acf3c1bb840>,
 <generator object <genexpr> at 0x7acf3c1bb920>,
 <generator object <genexpr> at 0x7acf3c1bba00>,
 <generator object <genexpr> at 0x7acf3c1bbae0>,
 <generator object <genexpr> at 0x7acf3c1bbbc0>,
 <generator object <genexpr> at 0x7acf3c1bbca0>,
 <generator object <genexpr> at 0x7acf3c1bbd80>,
 <generator object <genexpr> at 0x7acf3c1bbe60>,
 <generator object <genexpr> at 0x7acf3c13c040>,
 <generator object <genexpr> at 0x7acf3c13c120>,
 <generator object <genexpr> at 0x7acf3c13c200>,
 <generator object <genexpr> at 0x7acf3c13c2e0>,
 <generator object <genexpr> at 0x7acf3c13c3c0>,
 <generator object <genexpr> at 0x7acf3c13c4a0>,
 <generator object <genexpr> at 0x7acf3c13c580>,
 <generator object <genexpr> at 0x7acf3c13c660>,
 <generator object <genexpr> at 0x7acf3c13c740>,
 <generator object <genexpr> at 0x7acf3c13c820>,
 <generator object <genexpr> at 0x7acf3c13c900>,
 <generator object <genexpr> at 0x7acf3c13c9e0>,
 <generator object <genexpr> at 0x7acf3c13cac0>,
 <generator object <genexpr> at 0x7acf3c13cba0>,
 <generator object <genexpr> at 0x7acf3c13cc80>,
 <generator object <genexpr> at 0x7acf3c13cd60>,
 <generator object <genexpr> at 0x7acf3c13ce40>,
 <generator object <genexpr> at 0x7acf3c13cf20>,
 <generator object <genexpr> at 0x7acf3c13d000>,
 <generator object <genexpr> at 0x7acf3c13d0e0>,
 <generator object <genexpr> at 0x7acf3c13d1c0>,
 <generator object <genexpr> at 0x7acf3c13d2a0>,
 <generator object <genexpr> at 0x7acf3c13d380>,
 <generator object <genexpr> at 0x7acf3c13d460>,
 <generator object <genexpr> at 0x7acf3c13d540>,
 <generator object <genexpr> at 0x7acf3c13d620>,
 <generator object <genexpr> at 0x7acf3c13d700>,
 <generator object <genexpr> at 0x7acf3c13d7e0>,
 <generator object <genexpr> at 0x7acf3c13d8c0>,
 <generator object <genexpr> at 0x7acf3c13d9a0>,
 <generator object <genexpr> at 0x7acf3c13da80>,
 <generator object <genexpr> at 0x7acf3c13db60>,
 <generator object <genexpr> at 0x7acf3c13dc40>,
 <generator object <genexpr> at 0x7acf3c13dd20>,
 <generator object <genexpr> at 0x7acf3c13de00>,
 <generator object <genexpr> at 0x7acf3c13dee0>,
 <generator object <genexpr> at 0x7acf3c13dfc0>,
 <generator object <genexpr> at 0x7acf3c13e0a0>,
 <generator object <genexpr> at 0x7acf3c13e180>,
 <generator object <genexpr> at 0x7acf3c13e260>,
 <generator object <genexpr> at 0x7acf3c13e340>,
 <generator object <genexpr> at 0x7acf3c13e420>,
 <generator object <genexpr> at 0x7acf3c13e500>,
 <generator object <genexpr> at 0x7acf3c13e5e0>,
 <generator object <genexpr> at 0x7acf3c13e6c0>,
 <generator object <genexpr> at 0x7acf3c13e7a0>,
 <generator object <genexpr> at 0x7acf3c13e880>,
 <generator object <genexpr> at 0x7acf3c13e960>,
 <generator object <genexpr> at 0x7acf3c13ea40>,
 <generator object <genexpr> at 0x7acf3c13eb20>,
 <generator object <genexpr> at 0x7acf3c13ec00>,
 <generator object <genexpr> at 0x7acf3c13ece0>,
 <generator object <genexpr> at 0x7acf3c13edc0>,
 <generator object <genexpr> at 0x7acf3c13eea0>,
 <generator object <genexpr> at 0x7acf3c13ef80>,
 <generator object <genexpr> at 0x7acf3c13f060>,
 <generator object <genexpr> at 0x7acf3c13f140>,
 <generator object <genexpr> at 0x7acf3c13f220>,
 <generator object <genexpr> at 0x7acf3c13f300>,
 <generator object <genexpr> at 0x7acf3c13f3e0>,
 <generator object <genexpr> at 0x7acf3c13f4c0>,
 <generator object <genexpr> at 0x7acf3c13f5a0>,
 <generator object <genexpr> at 0x7acf3c13f680>,
 <generator object <genexpr> at 0x7acf3c13f760>,
 <generator object <genexpr> at 0x7acf3c13f840>,
 <generator object <genexpr> at 0x7acf3c13f920>,
 <generator object <genexpr> at 0x7acf3c13fa00>,
 <generator object <genexpr> at 0x7acf3c13fae0>,
 <generator object <genexpr> at 0x7acf3c13fbc0>,
 <generator object <genexpr> at 0x7acf3c13fca0>,
 <generator object <genexpr> at 0x7acf3c13fd80>,
 <generator object <genexpr> at 0x7acf3c13fe60>,
 <generator object <genexpr> at 0x7acf3c080040>,
 <generator object <genexpr> at 0x7acf3c080120>,
 <generator object <genexpr> at 0x7acf3c080200>,
 <generator object <genexpr> at 0x7acf3c0802e0>,
 <generator object <genexpr> at 0x7acf3c0803c0>,
 <generator object <genexpr> at 0x7acf3c0804a0>,
 <generator object <genexpr> at 0x7acf3c080580>,
 <generator object <genexpr> at 0x7acf3c080660>,
 <generator object <genexpr> at 0x7acf3c080740>,
 <generator object <genexpr> at 0x7acf3c080820>,
 <generator object <genexpr> at 0x7acf3c080900>,
 <generator object <genexpr> at 0x7acf3c0809e0>,
 <generator object <genexpr> at 0x7acf3c080ac0>,
 <generator object <genexpr> at 0x7acf3c080ba0>,
 <generator object <genexpr> at 0x7acf3c080c80>,
 <generator object <genexpr> at 0x7acf3c080d60>,
 <generator object <genexpr> at 0x7acf3c080e40>,
 <generator object <genexpr> at 0x7acf3c080f20>,
 <generator object <genexpr> at 0x7acf3c081000>,
 <generator object <genexpr> at 0x7acf3c0810e0>,
 <generator object <genexpr> at 0x7acf3c0811c0>,
 <generator object <genexpr> at 0x7acf3c0812a0>,
 <generator object <genexpr> at 0x7acf3c081380>,
 <generator object <genexpr> at 0x7acf3c081460>,
 <generator object <genexpr> at 0x7acf3c081540>,
 <generator object <genexpr> at 0x7acf3c081620>,
 <generator object <genexpr> at 0x7acf3c081700>,
 <generator object <genexpr> at 0x7acf3c0817e0>,
 <generator object <genexpr> at 0x7acf3c0818c0>,
 <generator object <genexpr> at 0x7acf3c0819a0>,
 <generator object <genexpr> at 0x7acf3c081a80>,
 <generator object <genexpr> at 0x7acf3c081b60>,
 <generator object <genexpr> at 0x7acf3c081c40>,
 <generator object <genexpr> at 0x7acf3c081d20>,
 <generator object <genexpr> at 0x7acf3c081e00>,
 <generator object <genexpr> at 0x7acf3c081ee0>,
 <generator object <genexpr> at 0x7acf3c081fc0>,
 <generator object <genexpr> at 0x7acf3c0820a0>,
 <generator object <genexpr> at 0x7acf3c082180>,
 <generator object <genexpr> at 0x7acf3c082260>,
 <generator object <genexpr> at 0x7acf3c082340>,
 <generator object <genexpr> at 0x7acf3c082420>,
 <generator object <genexpr> at 0x7acf3c082500>,
 <generator object <genexpr> at 0x7acf3c0825e0>,
 <generator object <genexpr> at 0x7acf3c0826c0>,
 <generator object <genexpr> at 0x7acf3c0827a0>,
 <generator object <genexpr> at 0x7acf3c082880>,
 <generator object <genexpr> at 0x7acf3c082960>,
 <generator object <genexpr> at 0x7acf3c082a40>,
 <generator object <genexpr> at 0x7acf3c082b20>,
 <generator object <genexpr> at 0x7acf3c082c00>,
 <generator object <genexpr> at 0x7acf3c082ce0>,
 <generator object <genexpr> at 0x7acf3c082dc0>,
 <generator object <genexpr> at 0x7acf3c082ea0>,
 <generator object <genexpr> at 0x7acf3c082f80>,
 <generator object <genexpr> at 0x7acf3c083060>,
 <generator object <genexpr> at 0x7acf3c083140>,
 <generator object <genexpr> at 0x7acf3c083220>,
 <generator object <genexpr> at 0x7acf3c083300>,
 <generator object <genexpr> at 0x7acf3c0833e0>,
 <generator object <genexpr> at 0x7acf3c0834c0>,
 <generator object <genexpr> at 0x7acf3c0835a0>,
 <generator object <genexpr> at 0x7acf3c083680>,
 <generator object <genexpr> at 0x7acf3c083760>,
 <generator object <genexpr> at 0x7acf3c083840>,
 <generator object <genexpr> at 0x7acf3c083920>,
 <generator object <genexpr> at 0x7acf3c083a00>,
 <generator object <genexpr> at 0x7acf3c083ae0>,
 <generator object <genexpr> at 0x7acf3c083bc0>,
 <generator object <genexpr> at 0x7acf3c083ca0>,
 <generator object <genexpr> at 0x7acf3c083d80>,
 <generator object <genexpr> at 0x7acf3c083e60>,
 <generator object <genexpr> at 0x7acf3c078040>,
 <generator object <genexpr> at 0x7acf3c078120>,
 <generator object <genexpr> at 0x7acf3c078200>,
 <generator object <genexpr> at 0x7acf3c0782e0>,
 <generator object <genexpr> at 0x7acf3c0783c0>,
 <generator object <genexpr> at 0x7acf3c0784a0>,
 <generator object <genexpr> at 0x7acf3c078580>,
 <generator object <genexpr> at 0x7acf3c078660>,
 <generator object <genexpr> at 0x7acf3c078740>,
 <generator object <genexpr> at 0x7acf3c078820>,
 <generator object <genexpr> at 0x7acf3c078900>,
 <generator object <genexpr> at 0x7acf3c0789e0>,
 <generator object <genexpr> at 0x7acf3c078ac0>,
 <generator object <genexpr> at 0x7acf3c078ba0>,
 <generator object <genexpr> at 0x7acf3c078c80>,
 <generator object <genexpr> at 0x7acf3c078d60>,
 <generator object <genexpr> at 0x7acf3c078e40>,
 <generator object <genexpr> at 0x7acf3c078f20>,
 <generator object <genexpr> at 0x7acf3c079000>,
 <generator object <genexpr> at 0x7acf3c0790e0>,
 <generator object <genexpr> at 0x7acf3c0791c0>,
 <generator object <genexpr> at 0x7acf3c0792a0>,
 <generator object <genexpr> at 0x7acf3c079380>,
 <generator object <genexpr> at 0x7acf3c079460>,
 <generator object <genexpr> at 0x7acf3c079540>,
 <generator object <genexpr> at 0x7acf3c079620>,
 <generator object <genexpr> at 0x7acf3c079700>,
 <generator object <genexpr> at 0x7acf3c0797e0>,
 <generator object <genexpr> at 0x7acf3c0798c0>,
 <generator object <genexpr> at 0x7acf3c0799a0>,
 <generator object <genexpr> at 0x7acf3c079a80>,
 <generator object <genexpr> at 0x7acf3c079b60>,
 <generator object <genexpr> at 0x7acf3c079c40>,
 <generator object <genexpr> at 0x7acf3c079d20>,
 <generator object <genexpr> at 0x7acf3c079e00>,
 <generator object <genexpr> at 0x7acf3c079ee0>,
 <generator object <genexpr> at 0x7acf3c079fc0>,
 <generator object <genexpr> at 0x7acf3c07a0a0>,
 <generator object <genexpr> at 0x7acf3c07a180>,
 <generator object <genexpr> at 0x7acf3c07a260>,
 <generator object <genexpr> at 0x7acf3c07a340>,
 <generator object <genexpr> at 0x7acf3c07a420>,
 <generator object <genexpr> at 0x7acf3c07a500>,
 <generator object <genexpr> at 0x7acf3c07a5e0>,
 <generator object <genexpr> at 0x7acf3c07a6c0>,
 <generator object <genexpr> at 0x7acf3c07a7a0>,
 <generator object <genexpr> at 0x7acf3c07a880>,
 <generator object <genexpr> at 0x7acf3c07a960>,
 <generator object <genexpr> at 0x7acf3c07aa40>,
 <generator object <genexpr> at 0x7acf3c07ab20>,
 <generator object <genexpr> at 0x7acf3c07ac00>,
 <generator object <genexpr> at 0x7acf3c07ace0>,
 <generator object <genexpr> at 0x7acf3c07adc0>,
 <generator object <genexpr> at 0x7acf3c07aea0>,
 <generator object <genexpr> at 0x7acf3c07af80>,
 <generator object <genexpr> at 0x7acf3c07b060>,
 <generator object <genexpr> at 0x7acf3c07b140>,
 <generator object <genexpr> at 0x7acf3c07b220>,
 <generator object <genexpr> at 0x7acf3c07b300>,
 <generator object <genexpr> at 0x7acf3c07b3e0>,
 <generator object <genexpr> at 0x7acf3c07b4c0>,
 <generator object <genexpr> at 0x7acf3c07b5a0>,
 <generator object <genexpr> at 0x7acf3c07b680>,
 <generator object <genexpr> at 0x7acf3c07b760>,
 <generator object <genexpr> at 0x7acf3c07b840>,
 <generator object <genexpr> at 0x7acf3c07b920>,
 <generator object <genexpr> at 0x7acf3c07ba00>,
 <generator object <genexpr> at 0x7acf3c07bae0>,
 <generator object <genexpr> at 0x7acf3c07bbc0>,
 <generator object <genexpr> at 0x7acf3c07bca0>,
 <generator object <genexpr> at 0x7acf3c07bd80>,
 <generator object <genexpr> at 0x7acf3c07be60>,
 <generator object <genexpr> at 0x7acf3c070040>,
 <generator object <genexpr> at 0x7acf3c070120>,
 <generator object <genexpr> at 0x7acf3c070200>,
 <generator object <genexpr> at 0x7acf3c0702e0>,
 <generator object <genexpr> at 0x7acf3c0703c0>,
 <generator object <genexpr> at 0x7acf3c0704a0>,
 <generator object <genexpr> at 0x7acf3c070580>,
 <generator object <genexpr> at 0x7acf3c070660>,
 <generator object <genexpr> at 0x7acf3c070740>,
 <generator object <genexpr> at 0x7acf3c070820>,
 <generator object <genexpr> at 0x7acf3c070900>,
 <generator object <genexpr> at 0x7acf3c0709e0>,
 <generator object <genexpr> at 0x7acf3c070ac0>,
 <generator object <genexpr> at 0x7acf3c070ba0>,
 <generator object <genexpr> at 0x7acf3c070c80>,
 <generator object <genexpr> at 0x7acf3c070d60>,
 <generator object <genexpr> at 0x7acf3c070e40>,
 <generator object <genexpr> at 0x7acf3c070f20>,
 <generator object <genexpr> at 0x7acf3c071000>,
 <generator object <genexpr> at 0x7acf3c0710e0>,
 <generator object <genexpr> at 0x7acf3c0711c0>,
 <generator object <genexpr> at 0x7acf3c0712a0>,
 <generator object <genexpr> at 0x7acf3c071380>,
 <generator object <genexpr> at 0x7acf3c071460>,
 <generator object <genexpr> at 0x7acf3c071540>,
 <generator object <genexpr> at 0x7acf3c071620>,
 <generator object <genexpr> at 0x7acf3c071700>,
 <generator object <genexpr> at 0x7acf3c0717e0>,
 <generator object <genexpr> at 0x7acf3c0718c0>,
 <generator object <genexpr> at 0x7acf3c0719a0>,
 <generator object <genexpr> at 0x7acf3c071a80>,
 <generator object <genexpr> at 0x7acf3c071b60>,
 <generator object <genexpr> at 0x7acf3c071c40>,
 <generator object <genexpr> at 0x7acf3c071d20>,
 <generator object <genexpr> at 0x7acf3c071e00>,
 <generator object <genexpr> at 0x7acf3c071ee0>,
 <generator object <genexpr> at 0x7acf3c071fc0>,
 <generator object <genexpr> at 0x7acf3c0720a0>,
 <generator object <genexpr> at 0x7acf3c072180>,
 <generator object <genexpr> at 0x7acf3c072260>,
 <generator object <genexpr> at 0x7acf3c072340>,
 <generator object <genexpr> at 0x7acf3c072420>,
 <generator object <genexpr> at 0x7acf3c072500>,
 <generator object <genexpr> at 0x7acf3c0725e0>,
 <generator object <genexpr> at 0x7acf3c0726c0>,
 <generator object <genexpr> at 0x7acf3c0727a0>,
 <generator object <genexpr> at 0x7acf3c072880>,
 <generator object <genexpr> at 0x7acf3c072960>,
 <generator object <genexpr> at 0x7acf3c072a40>,
 <generator object <genexpr> at 0x7acf3c072b20>,
 <generator object <genexpr> at 0x7acf3c072c00>,
 <generator object <genexpr> at 0x7acf3c072ce0>,
 <generator object <genexpr> at 0x7acf3c072dc0>,
 <generator object <genexpr> at 0x7acf3c072ea0>,
 <generator object <genexpr> at 0x7acf3c072f80>,
 <generator object <genexpr> at 0x7acf3c073060>,
 <generator object <genexpr> at 0x7acf3c073140>,
 <generator object <genexpr> at 0x7acf3c073220>,
 <generator object <genexpr> at 0x7acf3c073300>,
 <generator object <genexpr> at 0x7acf3c0733e0>,
 <generator object <genexpr> at 0x7acf3c0734c0>,
 <generator object <genexpr> at 0x7acf3c0735a0>,
 <generator object <genexpr> at 0x7acf3c073680>,
 <generator object <genexpr> at 0x7acf3c073760>,
 <generator object <genexpr> at 0x7acf3c073840>,
 <generator object <genexpr> at 0x7acf3c073920>,
 <generator object <genexpr> at 0x7acf3c073a00>,
 <generator object <genexpr> at 0x7acf3c073ae0>,
 <generator object <genexpr> at 0x7acf3c073bc0>,
 <generator object <genexpr> at 0x7acf3c073ca0>,
 <generator object <genexpr> at 0x7acf3c073d80>,
 <generator object <genexpr> at 0x7acf3c073e60>,
 <generator object <genexpr> at 0x7acf3c068040>,
 <generator object <genexpr> at 0x7acf3c068120>,
 <generator object <genexpr> at 0x7acf3c068200>,
 <generator object <genexpr> at 0x7acf3c0682e0>,
 <generator object <genexpr> at 0x7acf3c0683c0>,
 <generator object <genexpr> at 0x7acf3c0684a0>,
 <generator object <genexpr> at 0x7acf3c068580>,
 <generator object <genexpr> at 0x7acf3c068660>,
 <generator object <genexpr> at 0x7acf3c068740>,
 <generator object <genexpr> at 0x7acf3c068820>,
 <generator object <genexpr> at 0x7acf3c068900>,
 <generator object <genexpr> at 0x7acf3c0689e0>,
 <generator object <genexpr> at 0x7acf3c068ac0>,
 <generator object <genexpr> at 0x7acf3c068ba0>,
 <generator object <genexpr> at 0x7acf3c068c80>,
 <generator object <genexpr> at 0x7acf3c068d60>,
 <generator object <genexpr> at 0x7acf3c068e40>,
 <generator object <genexpr> at 0x7acf3c068f20>,
 <generator object <genexpr> at 0x7acf3c069000>,
 <generator object <genexpr> at 0x7acf3c0690e0>,
 <generator object <genexpr> at 0x7acf3c0691c0>,
 <generator object <genexpr> at 0x7acf3c0692a0>,
 <generator object <genexpr> at 0x7acf3c069380>,
 <generator object <genexpr> at 0x7acf3c069460>,
 <generator object <genexpr> at 0x7acf3c069540>,
 <generator object <genexpr> at 0x7acf3c069620>,
 <generator object <genexpr> at 0x7acf3c069700>,
 <generator object <genexpr> at 0x7acf3c0697e0>,
 <generator object <genexpr> at 0x7acf3c0698c0>,
 <generator object <genexpr> at 0x7acf3c0699a0>,
 <generator object <genexpr> at 0x7acf3c069a80>,
 <generator object <genexpr> at 0x7acf3c069b60>,
 <generator object <genexpr> at 0x7acf3c069c40>,
 <generator object <genexpr> at 0x7acf3c069d20>,
 <generator object <genexpr> at 0x7acf3c069e00>,
 <generator object <genexpr> at 0x7acf3c069ee0>,
 <generator object <genexpr> at 0x7acf3c069fc0>,
 <generator object <genexpr> at 0x7acf3c06a0a0>,
 <generator object <genexpr> at 0x7acf3c06a180>,
 <generator object <genexpr> at 0x7acf3c06a260>,
 <generator object <genexpr> at 0x7acf3c06a340>,
 <generator object <genexpr> at 0x7acf3c06a420>,
 <generator object <genexpr> at 0x7acf3c06a500>,
 <generator object <genexpr> at 0x7acf3c06a5e0>,
 <generator object <genexpr> at 0x7acf3c06a6c0>,
 <generator object <genexpr> at 0x7acf3c06a7a0>,
 <generator object <genexpr> at 0x7acf3c06a880>,
 <generator object <genexpr> at 0x7acf3c06a960>,
 <generator object <genexpr> at 0x7acf3c06aa40>,

In [6]:
from itertools import combinations

item_tidset = {}

for tid, transaction in enumerate(transactions):
    for item in transaction:
        if item not in item_tidset:
            item_tidset[item] = set()
        item_tidset[item].add(tid)

In [7]:
min_support_count = 20

In [8]:
frequent_itemsets = []

items = list(item_tidset.keys())

for item1, item2 in combinations(items, 2):

    common_tidset = item_tidset[item1] & item_tidset[item2]

    support_count = len(common_tidset)

    if support_count >= min_support_count:

        frequent_itemsets.append([
            item1,
            item2,
            support_count,
            support_count / len(transactions)
        ])

In [9]:
df_eclat = pd.DataFrame(
    frequent_itemsets,
    columns=[
        'Item 1',
        'Item 2',
        'Support Count',
        'Support'
    ]
)

df_eclat

            Item 1           Item 2  Support Count  Support
0             eggs  frozen smoothie           7501      1.0
1             eggs      yogurt cake           7501      1.0
2             eggs   low fat yogurt           7501      1.0
3             eggs              nan           7501      1.0
4  frozen smoothie      yogurt cake           7501      1.0
5  frozen smoothie   low fat yogurt           7501      1.0
6  frozen smoothie              nan           7501      1.0
7      yogurt cake   low fat yogurt           7501      1.0
8      yogurt cake              nan           7501      1.0
9   low fat yogurt              nan           7501      1.0

In [10]:
df_eclat = df_eclat.sort_values(
    by='Support',
    ascending=False
)

print(df_eclat.head(20))

            Item 1           Item 2  Support Count  Support
0             eggs  frozen smoothie           7501      1.0
1             eggs      yogurt cake           7501      1.0
2             eggs   low fat yogurt           7501      1.0
3             eggs              nan           7501      1.0
4  frozen smoothie      yogurt cake           7501      1.0
5  frozen smoothie   low fat yogurt           7501      1.0
6  frozen smoothie              nan           7501      1.0
7      yogurt cake   low fat yogurt           7501      1.0
8      yogurt cake              nan           7501      1.0
9   low fat yogurt              nan           7501      1.0